# Generated by Django 4.1.2 on 2022-11-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Published_Date', models.IntegerField(blank=True, null=True)),
                ('Author_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
        migrations.AlterField(
            model_name='add_studentdb',
            name='Password',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
