# Generated by Django 4.1.2 on 2022-11-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0003_alter_add_bookdb_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Products',
            name='Published_Date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
