# Generated by Django 4.1.2 on 2022-12-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0005_add_studentdb_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_studentdb',
            name='Password',
        ),
        migrations.AddField(
            model_name='add_studentdb',
            name='Mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
