# Generated by Django 4.1.2 on 2022-12-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0006_remove_add_studentdb_password_add_studentdb_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_studentdb',
            name='Rdate',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_studentdb',
            name='Tdate',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
