# Generated by Django 4.1.2 on 2023-01-01 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0009_add_categorydb_delete_add_studentdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_admindb',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='add_admindb',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='add_admindb',
            old_name='Mobile',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='add_admindb',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='add_admindb',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='Products',
            old_name='Author_name',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='Products',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='Products',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='Products',
            old_name='Published_Date',
            new_name='published_Date',
        ),
    ]
