# Generated by Django 4.1.2 on 2023-01-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0010_rename_email_add_admindb_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='Products',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
