# Generated by Django 4.1.2 on 2023-01-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0011_add_bookdb_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='Products',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
