# Generated by Django 4.1.2 on 2023-01-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0012_add_bookdb_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Products',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
