# Generated by Django 4.1.2 on 2023-01-05 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0017_rename_category_add_bookdb_bcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Products',
            old_name='bcategory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='Categorydb',
            old_name='cname',
            new_name='name',
        ),
    ]
