# Generated by Django 4.1.2 on 2023-01-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0019_rename_name_add_bookdb_bname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydb',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='Price',
        ),
        migrations.RemoveField(
            model_name='categorydb',
            name='cname',
        ),
        migrations.RemoveField(
            model_name='categorydb',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='products',
            name='bname',
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.RemoveField(
            model_name='products',
            name='published_Date',
        ),
        migrations.AddField(
            model_name='categorydb',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorydb',
            name='Name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='Categry',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='Name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='author_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='Published_Date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
