# Generated by Django 4.1.2 on 2023-01-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0020_rename_image_categorydb_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydb',
            name='Description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
