# Generated by Django 4.1.2 on 2023-01-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0021_alter_categorydb_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Published_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
