# Generated by Django 4.1.2 on 2023-01-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontapp', '0002_cartdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='Total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
