# Generated by Django 4.1.2 on 2023-01-19 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontapp', '0004_cartdb_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdb',
            name='Image',
        ),
    ]
