# Generated by Django 4.1.2 on 2023-01-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontapp', '0006_cartdb_name_cartdb_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdb',
            name='Price',
        ),
        migrations.AddField(
            model_name='cartdb',
            name='Author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
